### ISSUE TITLE
Undo Execution Listener Add does not update Prop Panel

### ISSUE THREAD

**Issue by meyerdan** [bpmn-io/bpmn-js-properties-panel#72]
Steps to reproduce:

add execution listener
perform undo => change is correctly reflected in model but the property panel is not re-rendered

**Comment by pedesen** [comment]
The properties panel is not updated, because the whole list of execution listeners is one single entry in the group 'executionListeners'. Instead every listener should be an entry itself. This should be fixed during investigating the undo/redo functionality.

**Comment by meyerdan** [comment]
Pushed a fix to branch. Testcases still missing (will not able to provide those now :/ )
